services:

  qr_bot:
    container_name: qrcode_bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: ["python", "main.py"]
    env_file:
      - .env
    environment:
      - API_KEY = ${API_KEY}